version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /reactApp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /reactApp/docker-credentials/password
    DOCKER_REGISTRY_URL: /reactApp/docker-registry/url
    
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 510786428272.dkr.ecr.us-east-1.amazonaws.com
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - export REPOSITORY_URI=510786428272.dkr.ecr.us-east-1.amazonaws.com/react-app
      - export TIMESTAMP=$(date +'%Y%m%d%H%M%S')
      - export IMAGE_TAG=latest-${TIMESTAMP}

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t react-app .
      - echo "Adding tag to Docker image..."
      - docker tag react-app :latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
